### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
May also want to change julia->Julia. At least Windows is a trademark, always wrong in lower case.

**Comment by PallHaraldsson** [comment]
Confusingly .travis.yml says tested on OS X, not Windows.. while README the opposite, both work?

**Comment by ig-or** [comment]
Thanks for your contribution!  I'll merge this soon (in the beginning of the next week?) I'm very new in all this github-related things.. 

Actually, I never worked with OS X; Travis maybe tested only that "using QWTwPlot" works.  But underlying qwtw "C" library was not ported on OS X - so on OS X this package is now useless; Maybe I should add this check and issue an error in case OS X?  what do you think?

**Comment by ig-or** [comment]
Páll, all was merged!

**Pull request merged**
